apiVersion: apps/v1
kind: Deployment #means type 
metadata:
  name: credit-card
spec:
  replicas: 3
  selector:
    matchLabels:
      app: credit-card
  template:
    metadata:
      labels:
        app: credit-card
    spec:
      containers:
      - name: credit-card
        image: credit-card:v1 #give image here
        resources: #we define here how much resources we want to give 
          limits:
            memory: "512Mi" #500mb memeory
            cpu: "200m" #1/5th of a core
        ports:
        - containerPort: 8080 #what we define in docker file put here
--- #this is for puting different yaml file in the same file
apiVersion: v1
kind: Service
metadata:
  name: credit-card
spec:
  selector:
    app: credit-card
  ports:
  - port: 1234 #for interacting with the cluster
    targetPort: 8080 #this port reun inside the container